Выполнена сборка проекта по технологии webpack
sostya/mesto pull request #1
Opened 2020-04-23 06:26 UTC by sostya

### Что сделано:

-  Создан репозиторий на GitHub;
-  Оформлено README.md;
-  Создан файл .gitignore с исключениями файлов;
-  Настроены три вида сборки: develop, build, production;
-  Настроено хеширование CSS и JS файлов;
-  Создан файл .nojekyll для возможности использования методологии БЭМ;
-  Настроен вебпак для работы с изображениями и их оптимизации;
-  Добавил раздел в конфигурацию Webpack для подгрузки шрифтов;
-  Код разбит на модули;
-  Сайт доступен на gh-pages, ссылка указана в readme;

2020-04-23 07:48 UTC, mrprovoker requested changes
Добрый день.

Отличная работа! Очень хорошее README, сборка проекта настроена корректно.

**Надо исправить:**
- Сайт по ссылке `http://sostya.github.io/mesto/` не открывается. Ветки gh-pages в репозитории нет. Необходимо выполнить данный пункт задания тоже.
- В index.html если закомментированный код. Данный код попадает в production-сборку. Необходимо удалить комментарии.


Можно лучше:
- В package.json в качестве main указан файл `index.js`. Такого файла в корне проекта нет, можно указать `src/index.js`.


При правках данный pull request закрывать/мерджить не надо. Все правки необходимо просто сделать новыми коммитами в этом же pull request'е.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-04-24 05:28 UTC, sostya commented
Здравствуйте. 
- Удалил комментарии в index.html. 
- Изменил путь в main в package.json
Проект на github-pages залил, ветку создал, но есть одна проблема, сайт полностью не загружается, выдает много 404 по js файлам, если его клонировать и запустить локально, все работает хорошо. Я пытался сделать страницу из develop или gh-pages репозиториев, но сайт выдает 404 (ждал некоторое время между попытками). По заданию сказано мерджить с мастер веткой только после того как работу примут :)

2020-04-25 05:04 UTC, mrprovoker requested changes
Спасибо за правки. 

По коду теперь замечаний нет, все отлично.

Но с github pages не получилось. Если зайти на https://sostya.github.io/mesto/ то видно, что верстка развалилась.


**Надо исправить:**
- Необходимо корретно залить на проект на github pages. Для этого в package.json есть скрипт `deploy`.
Соответственно заливается он туда двумя командами в консоле:
```
npm run build
npm run deploy
```


Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

2020-04-25 09:43 UTC, sostya commented
Ошибку исправил, сайт задеплоил, теперь отображается корректно

2020-04-25 10:56 UTC, mrprovoker approved these changes
Спасибо, теперь все отлично!

Все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

2020-04-25 12:12 UTC, merged